language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
## This is the ugliest form of testing but since this library doesn't have proper
## tests yet, this is the best way to test that it works on a basic level.
script: 
- python -c "from steamcareer import *"
- cd tests
- python -m unittest tests
# Opt-in for the container-based environment
sudo: false
